# Generated by Django 4.1.7 on 2023-11-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('bad_isbn', 'Bad Isbn'), ('saved_isbn', 'Saved Isbn'), ('pending_isbn', 'Pending Isbn'), ('blank_isbn', 'Blank Isbn')], default='blank_isbn', max_length=40),
        ),
    ]
