# Generated by Django 4.1.7 on 2023-11-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
